### ISSUE TITLE
How to use this repository with the Hands-on Unsupervised Learning Book? / Missing files 

### ISSUE THREAD

**Issue by ferencszalma** [aapatel09/handson-unsupervised-learning#19]
Missing

https://github.com/aapatel09/handson-unsupervised-learning/tree/master/datasets/credit_card_data/credit_card.csv

file. 

Otherwise very nice book. 🙂

**Comment by aapatel09** [comment]
Hi @szalmaf, could you please try this command to pull the data into the repo folder on your local environment?

aws s3 cp s3://handson-unsupervised-learning/datasets/ datasets --recursive --no-sign-request

The credit_card.csv file was too large to store on GitHub, so I moved it to S3.

The complete README instructions are here.
https://github.com/aapatel09/handson-unsupervised-learning#readme

Please do let me know if this works successfully for you because I just changed the instructions on Friday last week.

Thanks for the compliment!

**Comment by ferencszalma** [comment]
Hi @aapatel09, 

Thanks for the quick reply. In the meantime, I figured out that I could get the csv file from one of the forks of the repository.

I just tried the 'aws ...' command. It does not work for me. It gives the following error message:

Traceback (most recent call last):
  File "/usr/local/bin/aws", line 5, in <module>
    from aws.main import main
  File "/usr/local/lib/python3.8/site-packages/aws/main.py", line 23
    print '%(name)s: %(endpoint)s' % {
          ^
SyntaxError: invalid syntax

**Comment by aapatel09** [comment]
Thanks for following up on this. I know you have the data now, but could you please try to download the data using the **aws** command, too? I would like to troubleshoot the issue you're having, and hopefully this will be a resource for others in the future in case they encounter similar errors.

Let's try this please:
`aws s3 cp s3://handson-unsupervised-learning/datasets/ datasets --recursive --no-sign-request`

Please use the **aws** command line above using Command Prompt on Windows or Terminal on Mac. You should run this within the repo ***/handson-unsupervised-learning** so the data downloads directly into the datasets folder within the repo.

Also, did you pip install aws using this command on the command line? 
`pip install awscli==1.19.28`

If you would rather run these commands within the Jupyter notebook, please try this:
1. `!pip install awscli==1.19.28`
2. `!aws s3 cp s3://handson-unsupervised-learning/datasets/ datasets --recursive --no-sign-request`

I would love feedback on whether this solves this issue for you. Thanks!

**Comment by ferencszalma** [comment]
I am actually trying to use the data files from Google Colab.

As per you request, however, I tried the aws command again on my Mac laptop. After pip installing the exact version of awscli:

pip install awscli==1.19.28

and then cloning the handson-unsupervised-learning repo, cd-ing into it, the 

aws s3 cp s3://handson-unsupervised-learning/datasets/ datasets --recursive --no-sign-request

command did work and downloaded the csv and other files.

Hope this little test helps the repo to be developed further. And thanks for your prompt help.

**Comment by aapatel09** [comment]
Perfect. Glad to hear that this worked!
