### ISSUE TITLE
why not splitting them before scaling datasets 

### ISSUE THREAD

**Issue by TaiChiTiger** [aapatel09/handson-unsupervised-learning#3]
In your book, chapter2, if you scaling datasets first, it will leak the information of testing dataset.

**Comment by aapatel09** [comment]
Yes, excellent point. Will fix. 

Ankur

**Comment by TaiChiTiger** [comment]
Thank you for your reply!

**Comment by TaiChiTiger** [comment]
> Yes, excellent point. Will fix. Ankur
> […](#)
> On May 23, 2019, at 8:20 PM, TaichiTiger ***@***.***> wrote: In your book, chapter2, if you scaling datasets first, it will leak the information of testing dataset. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Thank you for your reply!
