### ISSUE TITLE
09_semisupervised - ValueError: Error when checking target: expected dense_3 to have shape (29,) but got array with shape (30,)

### ISSUE THREAD

**Issue by ghost** [aapatel09/handson-unsupervised-learning#9]
X_train has 30 columns but the input layer to the autoencoder expects 29. 
np.shape(X_train)
(193823, 30)

model = Sequential()
model.add(Dense(units=40, activation='linear', \
                activity_regularizer=regularizers.l1(10e-5), \
                input_dim=29,name='hidden_layer'))

Were you supposed to drop the Amount column in addition to Class and Time? 
dataX.columns
Index(['Unnamed: 0', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9',
       'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19',
       'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28',
       'Amount'],
      dtype='object')

**Comment by aapatel09** [comment]
Please drop 'Unnamed: 0' here. Looks like the index became a feature somehow. Does this resolve the issue?
